ARG version
FROM almalinux:${version:-9}
ARG COURSE=AWS
ARG TRAINER=Avin
ENV DURATION=120hrs
RUN echo "course is: ${COURSE} and trainer is: ${TRAINER} and duration is: ${DURATION}"
CMD ["sleep","100"]